In [8]:


import sqlite3
import pandas as pd

# 数据库连接
conn =  sqlite3.connect("../../../test.db")

# 读取表
df = pd.read_sql('select * from order_items',con = conn)

display(df)

display(df[['order_id','quantity','price']])

print("---------------------")

      id  order_id  product_id  quantity   price
0      1         1           1         1  6999.0
1      2         1           3         2  1999.0
2      3         2           6         3    89.0
3      4         2           8         1   399.0
4      5         2           9         2   199.0
..   ...       ...         ...       ...     ...
562  563       207           7         5   299.0
563  564       208           4         2  3999.0
564  565       208           7         4   299.0
565  566       208          30         4    59.0
566  567       208          26         1    89.0

[567 rows x 5 columns]

     order_id  quantity   price
0           1         1  6999.0
1           1         2  1999.0
2           2         3    89.0
3           2         1   399.0
4           2         2   199.0
..        ...       ...     ...
562       207         5   299.0
563       208         2  3999.0
564       208         4   299.0
565       208         4    59.0
566       208         1    89.0

[567 rows x 3 columns]

---------------------

In [6]:
"""
    df.to_sql(
    name,           # 表名
    con,            # 数据库连接对象
    if_exists='fail',  # 如果表已存在：'fail'报错，'replace'替换，'append'追加
    index=False     # 是否写入 DataFrame 索引行
"""
# 创建 DataFrame
data = {
    'order_id': [101, 102, 103],
    'price': [9.99, 15.49, 23.00]
}

df = pd.DataFrame(data)
print(df)
df.to_sql('test_items',con=conn,if_exists='replace',index=True)

conn.close()

   order_id  price
0       101   9.99
1       102  15.49
2       103  23.00