In [22]:
"""
        缺失值就是由某些原因导致部分数据为空，对于为空的这部分数据我们一般有两种处理
    方式，一种是删除，即把含有缺失值的数据删除；另外一种是填充，即把缺失的那部分数据
    用某个值代替。
"""

import pandas as pd
import numpy as np

df = pd.DataFrame([[1,2,np.nan],[4,np.nan,6],[5,6,7]])
df

   0    1    2
0  1  2.0  NaN
1  4  NaN  6.0
2  5  6.0  7.0

In [23]:
# 获取缺失值
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
 1   1       2 non-null      float64
 2   2       2 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 204.0 bytes

In [ ]:
"""
┌──────────────────────────────────────────────────────────────┐
│ <class 'pandas.core.frame.DataFrame'>                        │  ← 数据类型：这是一个 DataFrame
├──────────────────────────────────────────────────────────────┤
│ RangeIndex: 3 entries, 0 to 2                                │  ← 行索引范围：从 0 到 2，总 3 行
│ Data columns (total 3 columns):                              │  ← 列信息：总共 3 列
│
│ #   Column   Non-Null Count   Dtype                          │  ← 表头
│ 0   0        3 non-null       int64                          │  ← 第1列：列名0，3个非空，整数
│ 1   1        2 non-null       float64                        │  ← 第2列：列名1，2个非空，浮点数
│ 2   2        2 non-null       float64                        │  ← 第3列：列名2，2个非空，浮点数
├──────────────────────────────────────────────────────────────┤
│ dtypes: float64(2), int64(1)                                 │  ← 数据类型统计：2列浮点，1列整数
│ memory usage: 200.0 bytes                                    │  ← 内存占用大小
└──────────────────────────────────────────────────────────────┘
"""

In [25]:
"""
    isnull()  判断哪个值是缺失值，如果是缺失值则返回True，如果不是则会返回False
"""
df = pd.DataFrame([[1,2,np.nan],[4,np.nan,6],[5,6,7]])
df

   0    1    2
0  1  2.0  NaN
1  4  NaN  6.0
2  5  6.0  7.0

In [26]:
print("获取一维的缺失值")
df = pd.Series([1,2,np.nan,4,np.nan,6,5,6,7])
df[df.isnull()]

获取一维的缺失值

2   NaN
4   NaN
dtype: float64

In [34]:
df = pd.DataFrame([[1,2,np.nan],[4,np.nan,6],[5,6,7]])
print('isnull 方法判断是否是缺失值')
df.isnull()

isnull 方法判断是否是缺失值

   0    1    2
0  1  2.0  NaN
1  4  NaN  6.0
2  5  6.0  7.0

In [36]:
print(df.isnull())

       0      1      2
0  False  False   True
1  False   True  False
2  False  False  False

In [43]:
np.where(df.isnull())

(array([0, 1]), array([2, 1]))

In [44]:
print("获取一维的非空缺失值")
df = pd.Series([1,2,np.nan,4,np.nan,6,5,6,7])
df[df.notnull()]

获取一维的非空缺失值

0    1.0
1    2.0
3    4.0
5    6.0
6    5.0
7    6.0
8    7.0
dtype: float64