In [2]:
"""
    缺失值分为两种: 一种是一行中某个字段是缺失值；
                  另一种是一行中的字段全部为缺失值，即为一个空白行。

   删除缺失值函数：
         dropna()：默认删除含有缺失值的行，也就是只要某一行有缺失值就把这一行删除。如果想按列为单位删除缺失值，需要传入参数 axis=’columns’。
         返回删除后的结果
"""
import pandas as pd
import numpy as np

df = pd.DataFrame([[1,2,np.nan],[4,np.nan,6],[5,6,7]])
df

   0    1    2
0  1  2.0  NaN
1  4  NaN  6.0
2  5  6.0  7.0

In [3]:
print("以行为单位删除缺失值")
df.dropna()

以行为单位删除缺失值

   0    1    2
2  5  6.0  7.0

In [4]:
print("以列为单位删除缺失值")
df.dropna(axis=1)

以列为单位删除缺失值

   0
0  1
1  4
2  5

In [6]:
# 删除空白行
df=pd.DataFrame([[1,2,np.nan],[np.nan,np.nan,np.nan],[5,6,7]])
print("所有为nan时候才剔除")
df.dropna(how='all')
print("默认情况，只要有就剔除")
df.dropna(how='any')

     0    1    2
0  1.0  2.0  NaN
2  5.0  6.0  7.0