In [4]:
"""
               上面介绍了缺失值的删除，但是数据是宝贵的，一般情况下只要数据缺失比例不高（不大于 30%），尽量
    别删除，而是选择填充。调用 fillna()方法对数据表中的所有缺失值进行填充，在 fillna()方法中输入要填充的值。
    还可以通过 method 参数使用前一个数或后一个数来进行填充。

    Series.fillna(value=None, method=None, axis=None, inplace=False,limit=None, downcast=None)
    value ：用于填充缺失值的标量值或字典。如果传递的是字典，则字典的键应该是要填充的标签，值是用于填充的值。
    method ：字符串，表示填充的方法。可选值包括：
            pad / ffill ：用前一个非缺失值去填充缺失值。
            bfill / backfill ：用后一个非缺失值去填充缺失值。
    axis ：填充的轴，对于 Series 对象来说，这个参数通常不需要指定，因为Series 是一维的。
    inplace ：布尔值，表示是否在原地修改数据。如果为 True ，则直接在原Series 上修改，不返回新的对象。
    limit ：整数，表示最大填充量。如果指定，则只填充前 limit 个缺失值。
    downcast ：字典，用于向下转换数据类型。例如，可以将 float64 转换为float32 。
"""
import pandas as pd
import numpy as np


"""一维的缺失值填充"""
# 将所有缺失值全部填充为0
data=pd.Series([3,4,np.nan,1,5,None])
print("以0进行填充")
data.fillna(0)

以0进行填充

0    3.0
1    4.0
2    0.0
3    1.0
4    5.0
5    0.0
dtype: float64

In [5]:
# 前一个数填充与后一个数填充
print(data)
print("前填充")
data.ffill()

0    3.0
1    4.0
2    NaN
3    1.0
4    5.0
5    NaN
dtype: float64
前填充

0    3.0
1    4.0
2    4.0
3    1.0
4    5.0
5    5.0
dtype: float64

In [10]:
data=pd.Series([np.nan,4,np.nan,1,5,None])
print(data)
print("后填充")
data.bfill()
print("先后填充再前填充")
data.bfill().ffill()  # 可以保证所有的异常值都被填充

0    NaN
1    4.0
2    NaN
3    1.0
4    5.0
5    NaN
dtype: float64
后填充

0    4.0
1    4.0
2    1.0
3    1.0
4    5.0
5    5.0
dtype: float64

In [11]:
"""二维的缺失值填充"""
df=pd.DataFrame([[1,2,np.nan],[4,np.nan,6],[5,6,7]])
df

   0    1    2
0  1  2.0  NaN
1  4  NaN  6.0
2  5  6.0  7.0

In [13]:
print("以0进行填充")
df.fillna(0)

以0进行填充

   0    1    2
0  1  2.0  0.0
1  4  0.0  6.0
2  5  6.0  7.0

In [14]:
print('使用行的前一个数来填充：')
df.ffill()

使用行的前一个数来填充：

   0    1    2
0  1  2.0  NaN
1  4  2.0  6.0
2  5  6.0  7.0

In [15]:
print('使用列的后一个数来填充：')
df.bfill(axis=1)

使用列的后一个数来填充：

     0    1    2
0  1.0  2.0  NaN
1  4.0  6.0  6.0
2  5.0  6.0  7.0

In [19]:
# 列的平均数填充
df=pd.DataFrame([[1,2,np.nan],[4,np.nan,6],[5,6,7]])
print(df)

for i in df.columns:
    df[i]  = df[i].fillna(df[i].mean())

print(df)

   0    1    2
0  1  2.0  NaN
1  4  NaN  6.0
2  5  6.0  7.0
   0    1    2
0  1  2.0  6.5
1  4  4.0  6.0
2  5  6.0  7.0